---
- import_playbook: child_playbooks/hostname.yml
- import_playbook: child_playbooks/install_pkg.yml
- import_playbook: child_playbooks/config_nfs.yml
- import_playbook: child_playbooks/nfs_client.yml
